version: ~> 1.0
dist: focal
language: python
cache: pip
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
install: pip install -e .[test] codecov
script: ./run-tests.py
before_cache: rm -f $HOME/.cache/pip/log/debug.log
after_success: codecov
