dist: trusty
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
cache: pip
before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log
install:
  - pip install -e .
  - pip install "pytest>=3.1" pytest-cov coveralls
script: pytest
after_success: if [[ $TRAVIS_PYTHON_VERSION == 3.6* ]]; then coveralls; fi
