language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
cache: pip
before_cache: rm -f $HOME/.cache/pip/log/debug.log
install: pip install -e .[test] codecov
script: pytest
after_success: codecov
